"""ORM 模型汇总（40 张表，按 DATABASE.md 划分文件组织）。

导入本包即完成全部模型注册，Alembic autogenerate 与关系解析都依赖这一点。
"""

from app.db.base import Base
from app.models.ai import AIConversation, AIMessage, AIModelConfig, AIUsageLog
from app.models.challenge import Challenge, UserChallenge
from app.models.course import Chapter, Course, CourseEnrollment, Lesson, LessonTopic, Topic
from app.models.enums import (
    AchievementCategory,
    AIMessageKind,
    AIMessageRole,
    AIMode,
    AIProviderName,
    AIScene,
    AnnouncementLevel,
    BookmarkKind,
    ChallengeStatus,
    ChallengeType,
    CodeContextType,
    CodeSource,
    ComparisonMode,
    CourseLevel,
    Difficulty,
    ExamAttemptStatus,
    ExamLevel,
    LearningMode,
    LessonType,
    MasteryLevel,
    MistakeErrorType,
    NotificationType,
    ProblemCategory,
    ProblemType,
    ProgressStatus,
    RunnerType,
    SessionType,
    SubmissionStatus,
    TagKind,
    ThemePreference,
    UserProjectStatus,
    UserRole,
    UserStatus,
    enum_dict,
)
from app.models.exam import Exam, ExamAttempt
from app.models.gamification import Achievement, DailyTask, UserAchievement, UserDailyTask, XPTransaction
from app.models.learning import (
    Bookmark,
    CodeHistory,
    KnowledgeMastery,
    LearningProgress,
    LearningSession,
    Mistake,
)
from app.models.notification import Announcement, Notification
from app.models.problem import Problem, ProblemTag, Tag, TestCase
from app.models.project import Project, ProjectFile, UserProject
from app.models.submission import TERMINAL_STATUSES, Submission, SubmissionResult
from app.models.system import AuditLog, SystemSetting
from app.models.user import Profile, RefreshToken, User

#: 全部模型类（供建表、统计与自检使用）
ALL_MODELS = [
    User,
    Profile,
    RefreshToken,
    Course,
    Chapter,
    Lesson,
    Topic,
    LessonTopic,
    CourseEnrollment,
    Problem,
    TestCase,
    Tag,
    ProblemTag,
    Submission,
    SubmissionResult,
    Project,
    ProjectFile,
    UserProject,
    LearningProgress,
    KnowledgeMastery,
    Mistake,
    Bookmark,
    CodeHistory,
    LearningSession,
    Achievement,
    UserAchievement,
    DailyTask,
    UserDailyTask,
    XPTransaction,
    AIConversation,
    AIMessage,
    AIModelConfig,
    AIUsageLog,
    Challenge,
    UserChallenge,
    Exam,
    ExamAttempt,
    Notification,
    Announcement,
    AuditLog,
    SystemSetting,
]

__all__ = [
    "ALL_MODELS",
    "TERMINAL_STATUSES",
    "Achievement",
    "AchievementCategory",
    "AIConversation",
    "AIMessage",
    "AIMessageKind",
    "AIMessageRole",
    "AIModelConfig",
    "AIMode",
    "AIProviderName",
    "AIScene",
    "AIUsageLog",
    "Announcement",
    "AnnouncementLevel",
    "AuditLog",
    "Base",
    "Bookmark",
    "BookmarkKind",
    "Challenge",
    "ChallengeStatus",
    "ChallengeType",
    "Chapter",
    "CodeContextType",
    "CodeHistory",
    "CodeSource",
    "ComparisonMode",
    "Course",
    "CourseEnrollment",
    "CourseLevel",
    "DailyTask",
    "Difficulty",
    "Exam",
    "ExamAttempt",
    "ExamAttemptStatus",
    "ExamLevel",
    "KnowledgeMastery",
    "LearningMode",
    "LearningProgress",
    "LearningSession",
    "Lesson",
    "LessonTopic",
    "LessonType",
    "MasteryLevel",
    "Mistake",
    "MistakeErrorType",
    "Notification",
    "NotificationType",
    "Problem",
    "ProblemCategory",
    "ProblemTag",
    "ProblemType",
    "Profile",
    "ProgressStatus",
    "Project",
    "ProjectFile",
    "RefreshToken",
    "RunnerType",
    "SessionType",
    "Submission",
    "SubmissionResult",
    "SubmissionStatus",
    "SystemSetting",
    "Tag",
    "TagKind",
    "TestCase",
    "ThemePreference",
    "Topic",
    "User",
    "UserAchievement",
    "UserChallenge",
    "UserDailyTask",
    "UserProject",
    "UserProjectStatus",
    "UserRole",
    "UserStatus",
    "XPTransaction",
    "enum_dict",
]
