"""initial schema（PYTHON LAB 全量 41 张表，SQLite / PostgreSQL 双兼容）

Revision ID: 0001
Revises:
Create Date: 2026-09-27 10:04:16.323551
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到该版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('badge_color', sa.String(length=20), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index('ix_ach_active', ['is_active'], unique=False)
        batch_op.create_index('ix_ach_category', ['category'], unique=False)
        batch_op.create_index('ix_ach_code', ['code'], unique=True)

    op.create_table('ai_model_configs',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_env', sa.String(length=80), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capability_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_model_configs'))
    )
    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.create_index('ix_amc_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_amc_is_default', ['is_default'], unique=False)
        batch_op.create_index('ix_amc_provider', ['provider'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_al_action', ['action'], unique=False)
        batch_op.create_index('ix_al_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('ix_al_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_al_target_id', ['target_id'], unique=False)

    op.create_table('challenges',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('challenge_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('problem_ids_json', sa.JSON(), nullable=False),
    sa.Column('rules_md', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index('ix_challenges_end', ['end_at'], unique=False)
        batch_op.create_index('ix_challenges_published', ['is_published'], unique=False)
        batch_op.create_index('ix_challenges_slug', ['slug'], unique=True)
        batch_op.create_index('ix_challenges_start', ['start_at'], unique=False)
        batch_op.create_index('ix_challenges_type', ['challenge_type'], unique=False)

    op.create_table('courses',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_level', ['level'], unique=False)
        batch_op.create_index('ix_courses_order', ['order_index'], unique=False)
        batch_op.create_index('ix_courses_published', ['is_published'], unique=False)
        batch_op.create_index('ix_courses_slug', ['slug'], unique=True)
        batch_op.create_index('ix_courses_stage_no', ['stage_no'], unique=True)

    op.create_table('daily_tasks',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tasks'))
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_dt_active', ['is_active'], unique=False)
        batch_op.create_index('ix_dt_code', ['code'], unique=True)

    op.create_table('exams',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('question_ids_json', sa.JSON(), nullable=False),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index('ix_exams_code', ['code'], unique=True)
        batch_op.create_index('ix_exams_level', ['level'], unique=False)
        batch_op.create_index('ix_exams_published', ['is_published'], unique=False)

    op.create_table('projects',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=True),
    sa.Column('rubric_json', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_category', ['category'], unique=False)
        batch_op.create_index('ix_projects_level', ['level'], unique=False)
        batch_op.create_index('ix_projects_order', ['order_index'], unique=False)
        batch_op.create_index('ix_projects_published', ['is_published'], unique=False)
        batch_op.create_index('ix_projects_slug', ['slug'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('ix_ss_key', ['key'], unique=True)

    op.create_table('tags',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_kind', ['kind'], unique=False)
        batch_op.create_index('ix_tags_slug', ['slug'], unique=True)

    op.create_table('topics',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index('ix_topics_order', ['order_index'], unique=False)
        batch_op.create_index('ix_topics_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_topics_slug', ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('max_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_index('ix_users_level', ['level'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)
        batch_op.create_index('ix_users_status', ['status'], unique=False)
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_index('ix_users_xp', ['xp'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('scene', sa.String(length=20), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_aic_archived', ['is_archived'], unique=False)
        batch_op.create_index('ix_aic_context', ['context_type', 'context_id'], unique=False)
        batch_op.create_index('ix_aic_scene', ['scene'], unique=False)
        batch_op.create_index('ix_aic_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_aic_user_id', ['user_id'], unique=False)

    op.create_table('ai_usage_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('scene', sa.String(length=20), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_logs'))
    )
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_aul_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('ix_aul_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_aul_provider', ['provider'], unique=False)
        batch_op.create_index('ix_aul_success', ['success'], unique=False)
        batch_op.create_index('ix_aul_user_id', ['user_id'], unique=False)

    op.create_table('announcements',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('ix_ann_active', ['is_active'], unique=False)
        batch_op.create_index('ix_ann_pinned', ['is_pinned'], unique=False)
        batch_op.create_index('ix_ann_published', ['published_at'], unique=False)

    op.create_table('bookmarks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks'))
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bm_collection', ['collection'], unique=False)
        batch_op.create_index('ix_bm_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_bm_kind', ['kind'], unique=False)
        batch_op.create_index('ix_bm_ref', ['ref_id'], unique=False)
        batch_op.create_index('ix_bm_user_id', ['user_id'], unique=False)

    op.create_table('chapters',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_chapters_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('course_id', 'slug', name='uq_chapters_course_slug')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_course_id', ['course_id'], unique=False)
        batch_op.create_index('ix_chapters_order', ['order_index'], unique=False)

    op.create_table('code_history',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['code_history.id'], name=op.f('fk_code_history_parent_id_code_history'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_code_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_history'))
    )
    with op.batch_alter_table('code_history', schema=None) as batch_op:
        batch_op.create_index('ix_ch_context', ['context_type', 'context_id'], unique=False)
        batch_op.create_index('ix_ch_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_ch_user_id', ['user_id'], unique=False)

    op.create_table('course_enrollments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('completed_lessons', sa.Integer(), nullable=False),
    sa.Column('last_lesson_id', sa.String(length=36), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_enrollments')),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_ce_user_course')
    )
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_ce_course_id', ['course_id'], unique=False)
        batch_op.create_index('ix_ce_user_id', ['user_id'], unique=False)

    op.create_table('exam_attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_attempts_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempts'))
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_ea_exam_id', ['exam_id'], unique=False)
        batch_op.create_index('ix_ea_status', ['status'], unique=False)
        batch_op.create_index('ix_ea_user_id', ['user_id'], unique=False)

    op.create_table('knowledge_mastery',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.String(length=20), nullable=False),
    sa.Column('practiced_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_knowledge_mastery_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_mastery_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_mastery')),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_km_user_topic')
    )
    with op.batch_alter_table('knowledge_mastery', schema=None) as batch_op:
        batch_op.create_index('ix_km_level', ['mastery_level'], unique=False)
        batch_op.create_index('ix_km_next_review', ['next_review_at'], unique=False)
        batch_op.create_index('ix_km_score', ['mastery_score'], unique=False)
        batch_op.create_index('ix_km_topic_id', ['topic_id'], unique=False)
        batch_op.create_index('ix_km_user_id', ['user_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('learning_mode', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('actions_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_ls_mode', ['learning_mode'], unique=False)
        batch_op.create_index('ix_ls_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_ls_type', ['session_type'], unique=False)
        batch_op.create_index('ix_ls_user_id', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_nt_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_nt_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_nt_type', ['type'], unique=False)
        batch_op.create_index('ix_nt_user_id', ['user_id'], unique=False)

    op.create_table('problems',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('problem_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('sample_input', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('hint_md', sa.Text(), nullable=True),
    sa.Column('solution_md', sa.Text(), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('reference_solution', sa.Text(), nullable=True),
    sa.Column('buggy_code', sa.Text(), nullable=True),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('avg_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problems_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index('ix_problems_acceptance', ['acceptance_rate'], unique=False)
        batch_op.create_index('ix_problems_category', ['category'], unique=False)
        batch_op.create_index('ix_problems_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_problems_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_problems_published', ['is_published'], unique=False)
        batch_op.create_index('ix_problems_slug', ['slug'], unique=True)
        batch_op.create_index('ix_problems_title', ['title'], unique=False)
        batch_op.create_index('ix_problems_type', ['problem_type'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('theme_preference', sa.String(length=10), nullable=False),
    sa.Column('ai_mode', sa.String(length=20), nullable=False),
    sa.Column('learning_mode', sa.String(length=20), nullable=False),
    sa.Column('public_profile', sa.Boolean(), nullable=False),
    sa.Column('weekly_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('ix_profiles_display_name', ['display_name'], unique=False)
        batch_op.create_index('ix_profiles_user_id', ['user_id'], unique=True)

    op.create_table('project_files',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('is_entry', sa.Boolean(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_files_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_files')),
    sa.UniqueConstraint('project_id', 'path', name='uq_pf_project_path')
    )
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index('ix_pf_project_id', ['project_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_rt_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_rt_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_rt_jti', ['jti'], unique=True)
        batch_op.create_index('ix_rt_token_hash', ['token_hash'], unique=True)
        batch_op.create_index('ix_rt_user_id', ['user_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=36), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_ua_user_ach')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index('ix_ua_seen', ['seen'], unique=False)
        batch_op.create_index('ix_ua_user_id', ['user_id'], unique=False)

    op.create_table('user_challenges',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_user_challenges_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_challenges')),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_uc_user_challenge')
    )
    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.create_index('ix_uc_challenge_id', ['challenge_id'], unique=False)
        batch_op.create_index('ix_uc_rank', ['rank'], unique=False)
        batch_op.create_index('ix_uc_score', ['score'], unique=False)
        batch_op.create_index('ix_uc_status', ['status'], unique=False)
        batch_op.create_index('ix_uc_user_id', ['user_id'], unique=False)

    op.create_table('user_daily_tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('daily_task_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_tasks.id'], name=op.f('fk_user_daily_tasks_daily_task_id_daily_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_daily_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_daily_tasks')),
    sa.UniqueConstraint('user_id', 'daily_task_id', 'date', name='uq_udt_user_task_date')
    )
    with op.batch_alter_table('user_daily_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_udt_completed', ['completed'], unique=False)
        batch_op.create_index('ix_udt_date', ['date'], unique=False)
        batch_op.create_index('ix_udt_user_id', ['user_id'], unique=False)

    op.create_table('user_projects',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('files_json', sa.JSON(), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('last_run_status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_user_projects_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_projects')),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_up_user_project')
    )
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.create_index('ix_up_status', ['status'], unique=False)
        batch_op.create_index('ix_up_user_id', ['user_id'], unique=False)

    op.create_table('xp_transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_transactions'))
    )
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_xp_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_xp_reason', ['reason'], unique=False)
        batch_op.create_index('ix_xp_user_id', ['user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index('ix_aim_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('ix_aim_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_aim_kind', ['kind'], unique=False)

    op.create_table('lessons',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('has_playground', sa.Boolean(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('quiz_json', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_lessons_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('chapter_id', 'slug', name='uq_lessons_chapter_slug')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index('ix_lessons_chapter_id', ['chapter_id'], unique=False)
        batch_op.create_index('ix_lessons_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_lessons_order', ['order_index'], unique=False)
        batch_op.create_index('ix_lessons_published', ['is_published'], unique=False)
        batch_op.create_index('ix_lessons_type', ['lesson_type'], unique=False)

    op.create_table('problem_tags',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_tags_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_problem_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id', name=op.f('pk_problem_tags'))
    )
    with op.batch_alter_table('problem_tags', schema=None) as batch_op:
        batch_op.create_index('ix_pt_tag_id', ['tag_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('comparison', sa.String(length=20), nullable=False),
    sa.Column('float_tolerance', sa.Float(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_test_cases_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index('ix_tc_is_sample', ['is_sample'], unique=False)
        batch_op.create_index('ix_tc_order', ['order_index'], unique=False)
        batch_op.create_index('ix_tc_problem_id', ['problem_id'], unique=False)

    op.create_table('learning_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_learning_progress_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_progress')),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lp_user_lesson')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index('ix_lp_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('ix_lp_lesson_id', ['lesson_id'], unique=False)
        batch_op.create_index('ix_lp_status', ['status'], unique=False)
        batch_op.create_index('ix_lp_user_id', ['user_id'], unique=False)

    op.create_table('lesson_topics',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_topics_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_lesson_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'topic_id', name=op.f('pk_lesson_topics'))
    )
    with op.batch_alter_table('lesson_topics', schema=None) as batch_op:
        batch_op.create_index('ix_lt_lesson_id', ['lesson_id'], unique=False)
        batch_op.create_index('ix_lt_topic_id', ['topic_id'], unique=False)

    op.create_table('submissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('challenge_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_kb', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('runner', sa.String(length=20), nullable=False),
    sa.Column('judged_by', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_submissions_challenge_id_challenges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_submissions_lesson_id_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_submissions_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_sub_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sub_problem_id', ['problem_id'], unique=False)
        batch_op.create_index('ix_sub_problem_status', ['problem_id', 'status'], unique=False)
        batch_op.create_index('ix_sub_status', ['status'], unique=False)
        batch_op.create_index('ix_sub_user_created', ['user_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('ix_sub_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_sub_user_problem', ['user_id', 'problem_id'], unique=False)

    op.create_table('mistakes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=True),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('question_snapshot_md', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('note_md', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_mistakes_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_mistakes_submission_id_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_mistakes_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mistakes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes'))
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.create_index('ix_mk_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_mk_error_type', ['error_type'], unique=False)
        batch_op.create_index('ix_mk_next_review', ['next_review_at'], unique=False)
        batch_op.create_index('ix_mk_problem_id', ['problem_id'], unique=False)
        batch_op.create_index('ix_mk_resolved', ['resolved'], unique=False)
        batch_op.create_index('ix_mk_user_id', ['user_id'], unique=False)

    op.create_table('submission_results',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_kb', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_submission_results_submission_id_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], name=op.f('fk_submission_results_test_case_id_test_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_results'))
    )
    with op.batch_alter_table('submission_results', schema=None) as batch_op:
        batch_op.create_index('ix_sr_submission_id', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚该版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_results', schema=None) as batch_op:
        batch_op.drop_index('ix_sr_submission_id')

    op.drop_table('submission_results')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index('ix_mk_user_id')
        batch_op.drop_index('ix_mk_resolved')
        batch_op.drop_index('ix_mk_problem_id')
        batch_op.drop_index('ix_mk_next_review')
        batch_op.drop_index('ix_mk_error_type')
        batch_op.drop_index('ix_mk_created_at')

    op.drop_table('mistakes')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_sub_user_problem')
        batch_op.drop_index('ix_sub_user_id')
        batch_op.drop_index('ix_sub_user_created')
        batch_op.drop_index('ix_sub_status')
        batch_op.drop_index('ix_sub_problem_status')
        batch_op.drop_index('ix_sub_problem_id')
        batch_op.drop_index('ix_sub_created_at')

    op.drop_table('submissions')
    with op.batch_alter_table('lesson_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_lt_topic_id')
        batch_op.drop_index('ix_lt_lesson_id')

    op.drop_table('lesson_topics')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_lp_user_id')
        batch_op.drop_index('ix_lp_status')
        batch_op.drop_index('ix_lp_lesson_id')
        batch_op.drop_index('ix_lp_completed_at')

    op.drop_table('learning_progress')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_tc_problem_id')
        batch_op.drop_index('ix_tc_order')
        batch_op.drop_index('ix_tc_is_sample')

    op.drop_table('test_cases')
    with op.batch_alter_table('problem_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_pt_tag_id')

    op.drop_table('problem_tags')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('ix_lessons_type')
        batch_op.drop_index('ix_lessons_published')
        batch_op.drop_index('ix_lessons_order')
        batch_op.drop_index('ix_lessons_difficulty')
        batch_op.drop_index('ix_lessons_chapter_id')

    op.drop_table('lessons')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_aim_kind')
        batch_op.drop_index('ix_aim_created_at')
        batch_op.drop_index('ix_aim_conversation_id')

    op.drop_table('ai_messages')
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_xp_user_id')
        batch_op.drop_index('ix_xp_reason')
        batch_op.drop_index('ix_xp_created_at')

    op.drop_table('xp_transactions')
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_up_user_id')
        batch_op.drop_index('ix_up_status')

    op.drop_table('user_projects')
    with op.batch_alter_table('user_daily_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_udt_user_id')
        batch_op.drop_index('ix_udt_date')
        batch_op.drop_index('ix_udt_completed')

    op.drop_table('user_daily_tasks')
    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_uc_user_id')
        batch_op.drop_index('ix_uc_status')
        batch_op.drop_index('ix_uc_score')
        batch_op.drop_index('ix_uc_rank')
        batch_op.drop_index('ix_uc_challenge_id')

    op.drop_table('user_challenges')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_ua_user_id')
        batch_op.drop_index('ix_ua_seen')

    op.drop_table('user_achievements')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_rt_user_id')
        batch_op.drop_index('ix_rt_token_hash')
        batch_op.drop_index('ix_rt_jti')
        batch_op.drop_index('ix_rt_expires_at')
        batch_op.drop_index('ix_rt_created_at')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index('ix_pf_project_id')

    op.drop_table('project_files')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_profiles_user_id')
        batch_op.drop_index('ix_profiles_display_name')

    op.drop_table('profiles')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index('ix_problems_type')
        batch_op.drop_index('ix_problems_title')
        batch_op.drop_index('ix_problems_slug')
        batch_op.drop_index('ix_problems_published')
        batch_op.drop_index('ix_problems_difficulty')
        batch_op.drop_index('ix_problems_created_at')
        batch_op.drop_index('ix_problems_category')
        batch_op.drop_index('ix_problems_acceptance')

    op.drop_table('problems')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_nt_user_id')
        batch_op.drop_index('ix_nt_type')
        batch_op.drop_index('ix_nt_is_read')
        batch_op.drop_index('ix_nt_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_ls_user_id')
        batch_op.drop_index('ix_ls_type')
        batch_op.drop_index('ix_ls_started_at')
        batch_op.drop_index('ix_ls_mode')

    op.drop_table('learning_sessions')
    with op.batch_alter_table('knowledge_mastery', schema=None) as batch_op:
        batch_op.drop_index('ix_km_user_id')
        batch_op.drop_index('ix_km_topic_id')
        batch_op.drop_index('ix_km_score')
        batch_op.drop_index('ix_km_next_review')
        batch_op.drop_index('ix_km_level')

    op.drop_table('knowledge_mastery')
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_ea_user_id')
        batch_op.drop_index('ix_ea_status')
        batch_op.drop_index('ix_ea_exam_id')

    op.drop_table('exam_attempts')
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_ce_user_id')
        batch_op.drop_index('ix_ce_course_id')

    op.drop_table('course_enrollments')
    with op.batch_alter_table('code_history', schema=None) as batch_op:
        batch_op.drop_index('ix_ch_user_id')
        batch_op.drop_index('ix_ch_created_at')
        batch_op.drop_index('ix_ch_context')

    op.drop_table('code_history')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_chapters_order')
        batch_op.drop_index('ix_chapters_course_id')

    op.drop_table('chapters')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('ix_bm_user_id')
        batch_op.drop_index('ix_bm_ref')
        batch_op.drop_index('ix_bm_kind')
        batch_op.drop_index('ix_bm_created_at')
        batch_op.drop_index('ix_bm_collection')

    op.drop_table('bookmarks')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('ix_ann_published')
        batch_op.drop_index('ix_ann_pinned')
        batch_op.drop_index('ix_ann_active')

    op.drop_table('announcements')
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_aul_user_id')
        batch_op.drop_index('ix_aul_success')
        batch_op.drop_index('ix_aul_provider')
        batch_op.drop_index('ix_aul_created_at')
        batch_op.drop_index('ix_aul_conversation_id')

    op.drop_table('ai_usage_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_aic_user_id')
        batch_op.drop_index('ix_aic_updated_at')
        batch_op.drop_index('ix_aic_scene')
        batch_op.drop_index('ix_aic_context')
        batch_op.drop_index('ix_aic_archived')

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_xp')
        batch_op.drop_index('ix_users_username')
        batch_op.drop_index('ix_users_status')
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_level')
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_slug')
        batch_op.drop_index('ix_topics_parent_id')
        batch_op.drop_index('ix_topics_order')

    op.drop_table('topics')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_slug')
        batch_op.drop_index('ix_tags_kind')

    op.drop_table('tags')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_ss_key')

    op.drop_table('system_settings')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_slug')
        batch_op.drop_index('ix_projects_published')
        batch_op.drop_index('ix_projects_order')
        batch_op.drop_index('ix_projects_level')
        batch_op.drop_index('ix_projects_category')

    op.drop_table('projects')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('ix_exams_published')
        batch_op.drop_index('ix_exams_level')
        batch_op.drop_index('ix_exams_code')

    op.drop_table('exams')
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_dt_code')
        batch_op.drop_index('ix_dt_active')

    op.drop_table('daily_tasks')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_stage_no')
        batch_op.drop_index('ix_courses_slug')
        batch_op.drop_index('ix_courses_published')
        batch_op.drop_index('ix_courses_order')
        batch_op.drop_index('ix_courses_level')

    op.drop_table('courses')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_type')
        batch_op.drop_index('ix_challenges_start')
        batch_op.drop_index('ix_challenges_slug')
        batch_op.drop_index('ix_challenges_published')
        batch_op.drop_index('ix_challenges_end')

    op.drop_table('challenges')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_al_target_id')
        batch_op.drop_index('ix_al_created_at')
        batch_op.drop_index('ix_al_actor_id')
        batch_op.drop_index('ix_al_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_amc_provider')
        batch_op.drop_index('ix_amc_is_default')
        batch_op.drop_index('ix_amc_is_active')

    op.drop_table('ai_model_configs')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_ach_code')
        batch_op.drop_index('ix_ach_category')
        batch_op.drop_index('ix_ach_active')

    op.drop_table('achievements')
    # ### end Alembic commands ###
